sudo: false
language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_828219c472e1_key -iv $encrypted_828219c472e1_iv
  -in Who-am-I-48823a1c948f.json.enc -out Who-am-I-48823a1c948f.json -d
install:
- yarn install
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Who-am-I-48823a1c948f.json
  project: who-am-i-232019
  default: true
  on:
    all_branches: true
