const experience = [
  {
    id: "wayfair",
    from: "June 2019",
    to: "Present",
    employer: "Wayfair",
    domain: "eCommerce",
    nextEmpId: "expedia",
    prevEmpId: "",
    details: [
      {
        role: "Senior Software Engineer",
        responsibilities: [
          "Storefront - Alternative Financing",
          "More responsibilty 1",
          "More responsibilty 2",
          "More responsibilty 3 More responsibilty 3 More responsibilty 3 More responsibilty 3 More responsibilty 3",
          "More responsibilty 4 More responsibilty 4 More responsibilty 4 More responsibilty 4 More responsibilty 4 More responsibilty 4 More responsibilty 4 More responsibilty 4",
          "More responsibilty 5 More responsibilty 5 More responsibilty 5 More responsibilty 5 More responsibilty 5 More responsibilty 5",
        ],
      },
      {
        role: "Full Stack Engineer",
        responsibilities: [
          "Sotrefront - Registry",
          "Create scalable react apps",
          "working on storefront- registry team",
          "Be proactive and work on production alerts and issues",
          "A canditate for Wayfair registry third party integration. Communicate with the Merchants and 3rd party providers",
          "Worked and delivered a project for the registry team. To try out, create a registry in wayfair.com/registry and after you login you should be landing on the registry quiz experience. Hopefully its still there.",
          "More responsibilty",
        ],
      },
    ],
    skillsSet: [
      { percent: 100, text: "React", color: "red" },
      { percent: 90, text: "Redux", color: "blue" },
      { percent: 80, text: "PHP", color: "green" },
      { percent: 75, text: "Java", color: "orange" },
    ],
  },
  {
    id: "expedia",
    from: "May 2018",
    to: "June 2019",
    employer: "KFORCE - Expedia",
    domain: "TRAVEL AND HOSPITALITY",
    prevEmpId: "wayfair",
    nextEmpId: "wipro",
    details: [
      {
        role: "Full Stack Engineer",
        responsibilities: [
          "Created re-suable React component with limited props, with the help of Mobx viewstore and models",
          "Handling the react state with Mobx, with the observe-observer pattern",
          "Handling the react state with Mobx, with the observe-observer pattern",
          "Application perfroms array and object operations where large data sets are expected",
          "Polyflills(Babel) are used support all the browsers while leveraging the ES6 features",
          "CSS is compiled from less",
          "CSS is coded ensuring interface is available on all browsers",
          "Yarn is used and the build manager and serving the live application for development",
          "Serviceworkers are used to enhance the offline capabilities of the app",
          "Created a service in spring boot connecting to 3rd party end points",
          "Generating PDF and CSV on fly",
          "Use GIT for collaborating development effort",
          "Create branches and PRs for different cards assigned",
          "Review PRs and address review comment ensuring the best version is merged",
          "Demo the application enhancements and bugs fixed for every 2 weeks",
          "Participate in analyzing and judging the efforts in sprint planning",
          "Supporting production deployment on rotation basis",
          "Be prompt on the feedback channel and be able to judge and fix P1 and P0 prod issues",
        ],
      },
    ],
    skillsSet: [
      { percent: 100, text: "React", color: "red" },
      { percent: 90, text: "MOB-X", color: "blue" },
      { percent: 80, text: "Java", color: "orange" },
      { percent: 80, text: "SPRING", color: "green" },
    ],
  },
  {
    id: "wipro",
    from: "Sept 2010",
    to: "May 2018",
    employer: "Wipro",
    domain: "Service Provider",
    prevEmpId: "expedia",
    nextEmpId: "",
    details: [
      {
        role: "Full Stack Engineer",
        responsibilities: [
          "Created re-suable React component with limited props, with the help of Mobx viewstore and models",
          "Handling the react state with Mobx, with the observe-observer pattern",
          "Handling the react state with Mobx, with the observe-observer pattern",
          "Application perfroms array and object operations where large data sets are expected",
          "Polyflills(Babel) are used support all the browsers while leveraging the ES6 features",
          "CSS is compiled from less",
          "CSS is coded ensuring interface is available on all browsers",
          "Yarn is used and the build manager and serving the live application for development",
          "Serviceworkers are used to enhance the offline capabilities of the app",
          "Created a service in spring boot connecting to 3rd party end points",
          "Generating PDF and CSV on fly",
          "Use GIT for collaborating development effort",
          "Create branches and PRs for different cards assigned",
          "Review PRs and address review comment ensuring the best version is merged",
          "Demo the application enhancements and bugs fixed for every 2 weeks",
          "Participate in analyzing and judging the efforts in sprint planning",
          "Supporting production deployment on rotation basis",
          "Be prompt on the feedback channel and be able to judge and fix P1 and P0 prod issues",
        ],
      },
    ],
    skillsSet: [
      { percent: 100, text: "SAP", color: "red" },
      { percent: 70, text: "Java", color: "blue" },
      { percent: 60, text: "SAP UI5", color: "orange" },
      { percent: 60, text: "JS", color: "green" },
    ],
  },
];

export default experience;
